### ISSUE TITLE
Tree always opens in Full Screen

### ISSUE THREAD

**Issue by behinddwalls** [mariusor/bubbles-tree#1]
I followed the example but the tree always opens up in the full screen even when AltOption is not provided.

Is is by default or am i missing something?

**Comment by mariusor** [comment]
Hey @behinddwalls, apologies for the late reply, I was not paying attention to the issue tracker.

The reason why the top is not collapsed is because that's how we build the tree, if the node doesn't have a parent (only a root node would match this condition), we don't add the `NodeCollapsed` attribute. See [here](https://github.com/mariusor/bubbles-tree/blob/master/examples/tree/main.go#L118)
